name: Deploy Documentation to gh-pages

on:
  workflow_run:
    workflows: ["Test Deploy Versioned Pages"]  
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
      pages: write
      id-token: write

    steps:
      # Step 1: Check out the deployment repository
      - name: Checkout Deployment Repository
        uses: actions/checkout@v4


      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: docs-build  


      - name: Run Custom Deploy Action 🚀
        uses: ./.github/actions/deploy-versioned-pages
        with:
          source_folder: "docs-build"  
          versions_file: "versions"
          create_comment: "true"
