name: Test License Check

on:
  workflow_dispatch:
  push:
  pull_request:

    
jobs:
  call-license-check:
    uses: qorix-group/cicd-workflows/.github/workflows/license-check.yml@dcalavrzo_dash
    with:
      repo-url: https://github.com/dcalavrezo-qorix/gh-page-test
      bazel-target: "run //:license-check"
    secrets:
      gitlab-api-token: ${{ secrets.ECLIPSE_GITLAB_API_TOKEN }}
