name: Test Deploy Versioned Pages

on:
  pull_request_target:
    types: [opened, synchronize, closed]
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Base Branch
        uses: actions/checkout@v4
        with:
            ref: ${{ github.event.pull_request.head.sha }}

          
      - name: Run Custom Deploy Action 🚀
        uses: ./.github/actions/deploy-versioned-pages
        with:
          source_folder: "docs/build"  # Change to an actual test folder
          versions_file: "versions"
          create_comment: "true"