name: Test Deploy Versioned Pages

on:
  pull_request:
    types: [opened, synchronize, closed]
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: gh-pages-deploy
    permissions:
        contents: write  # ✅ Required for pushing to gh-pages
        pages: write
        id-token: write    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

    - name: Debug: Check If Token is Passed
    run: |
          if [ -z "${{ secrets.GH_PAGES_DEPLOY_TOKEN }}" ]; then
            echo "❌ ERROR: GH_PAGES_DEPLOY_TOKEN is empty!"
            exit 1
          else
            echo "✅ GH_PAGES_DEPLOY_TOKEN is available."
          fi        

      - name: Run Custom Deploy Action 🚀
        uses: ./.github/actions/deploy-versioned-pages
        with:
          source_folder: "docs/build"  # Change to an actual test folder
          versions_file: "versions"
          create_comment: "true"
          gh_token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}

